-- MySQL Script generated by MySQL Workbench
-- Sun Jul 19 13:54:53 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema partners_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema partners_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `partners_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `partners_db` ;

-- -----------------------------------------------------
-- Table `partners_db`.`material_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `partners_db`.`material_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(100) NULL DEFAULT NULL,
  `defect` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `partners_db`.`partner_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `partners_db`.`partner_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `partners_db`.`partners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `partners_db`.`partners` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `type_id` INT NULL DEFAULT NULL,
  `rating` INT NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `director` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `type_id` (`type_id` ASC),
  CONSTRAINT `partners_ibfk_1`
    FOREIGN KEY (`type_id`)
    REFERENCES `partners_db`.`partner_types` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `partners_db`.`product_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `partners_db`.`product_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(100) NULL DEFAULT NULL,
  `coefficient` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `partners_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `partners_db`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `type_id` INT NULL DEFAULT NULL,
  `param1` DOUBLE NULL DEFAULT NULL,
  `param2` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `type_id` (`type_id` ASC),
  CONSTRAINT `products_ibfk_1`
    FOREIGN KEY (`type_id`)
    REFERENCES `partners_db`.`product_types` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `partners_db`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `partners_db`.`sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `partner_id` INT NULL DEFAULT NULL,
  `product_id` INT NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `sale_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `partner_id` (`partner_id` ASC),
  INDEX `product_id` (`product_id` ASC),
  CONSTRAINT `sales_ibfk_1`
    FOREIGN KEY (`partner_id`)
    REFERENCES `partners_db`.`partners` (`id`),
  CONSTRAINT `sales_ibfk_2`
    FOREIGN KEY (`product_id`)
    REFERENCES `partners_db`.`products` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
